### ISSUE TITLE
Support for markdown code blocks

### ISSUE THREAD

**Issue by g13013** [qjebbs/vscode-plantuml#14]
It would be awesome to have support for markdown
```md
`` `uml or plantuml

class1 --> class2

`` `
```

**Comment by qjebbs** [comment]
what do you mean? Do you want to write plantuml codes directly in MD? This is beyond what this plugin can do, because I cannot change markdown plugin behavior.

You can generate url for diagram, copy&paste them in MD doc, should work. 

Or, name the diagrams, which makes output images in a consistent path, reference them in MD. Each time you re-generate images, MD updates.

**Comment by g13013** [comment]
I don't know how vscode estensions api work, but I was hoping it could bring syntax colors !

**Comment by qjebbs** [comment]
Highlight in markdown document is contributed by markdown plugin, just like plantuml highlight is by my plugin. In other words, your request should be done in markdown plugin, it's out of my reach.
