### ISSUE TITLE
Include with relative path doesn't work

### ISSUE THREAD

**Issue by DavidExtern** [qjebbs/vscode-plantuml#158]
Hi,

After the last update, all include with relative path are broken. I work on MacOS Mojave
Exemple : 
- workspace path : /Users/me/workspace
- file path : 
      /Users/me/workspace/src/file.puml
      /Users/me/workspace/src/inc.puml

file "file.puml"
```
@startuml
!include inc.puml
@enduml
```

My error on vscode
```Error
Cannot include /Users/me/workspace/./inc.puml
```

**Comment by kosfed** [comment]
Hi,
I have the same issue after last update.
It runs plantuml.jar from root workspace directory and relative paths don't work properly, they have wrong base.
Workspace absolute path: c:\users\XXX\diagrams\
Included file absolute path: c:\users\XXX\diagrams\helpers\common.puml
My diagram file absolute path and code: c:\users\XXX\diagrams\data_sources\my_diagram.puml
`!include "../helpers/common.puml"`

Error message:
`Cannot include c:\users\XXX\diagrams\.\..\helpers\common.puml`

If open in VSCode folder with rendering file directly it works.
Do anyone have ideas how to set execution path to be equal to rendering file location or when it could be fixed?

**Comment by qjebbs** [comment]
Yes, I did change the include search logic,  because I found new logic helps you right same include path over all files in the project.

@DavidExtern if your files are all in `src` dir (both including file and other source files, no sub dirs) , you may:

```
plantuml.diagramsRoot: 'src'
```

no more changes needed, it should be OK.

@kosfed if you have many sub dirs, you may need to change sources, but still recommend to set the `diagramsRoot`. The benefits is, after doing this, you don't have to change include path when you re-organize your files, like move a file to parent dir.

**Comment by qjebbs** [comment]
If so many people think this adjustment is a problem, I will provide a setting to restore old logic.

**Comment by kosfed** [comment]
Thanks @qjebbs. I have a lot of inherited diagrams and it's a bit borring to change them all.
Could you add option to specify what logic is used?

**Comment by DavidExtern** [comment]
@qjebbs : I don't have all my include files in the same repository. So all files render is blocked.
```
/Users/me/workspace/src/file.puml
/Users/me/workspace/src/inc.puml
 /Users/me/workspace/src1/file.puml
/Users/me/workspace/src1/file.puml
 /Users/me/workspace/src2/file.puml
/Users/me/workspace/src2/file.puml
```

**Comment by qjebbs** [comment]
OK, soon I will provide the setting...

**Comment by kosfed** [comment]
Great, thanks a lot.

**Comment by qjebbs** [comment]
Please update to 2.9.7.

See also `README - Notice 1`:

Latest version has changed the include files seach logic, it's based on fixed path to workspace folder.

If you encounter include problem in your existed projects, to restore previous logic, please add following in workspace settings:

```json
"plantuml.includeSearch": "Relative",
```

To new projects, it's recommended to use fixed path, since it's more easy to manage.

**Comment by DavidExtern** [comment]
It's work, thanks a lot ! Very nice job !
