### ISSUE TITLE
Latest version fails to apply -SfixCircleLabelOverlapping=true

### ISSUE THREAD

**Issue by sandersaares** [qjebbs/vscode-plantuml#163]
I notice that the plugin was recently updated to a version of PlantUML that includes the following defect: http://forum.plantuml.net/8442/regression-in-2018-03-2018-11-component-diagram-layout

I tried to use the workaround described by PlantUML developers and adding the following setting in VSCode settings:

```
	"plantuml.commandArgs": ["-SfixCircleLabelOverlapping=true"],
```

However, this results in a failure of the preview to render.

![image](https://user-images.githubusercontent.com/9914262/47478876-d26b9e00-d833-11e8-8bdc-359bd624e174.png)

Please advise if I am doing something wrong or what is the right way to work around this defect when rendering diagrams with the VSCode plugin.

**Comment by sandersaares** [comment]
Oh hang on, there is also `jarArgs`. That one works.

To me as a user it is very confusing to see two ways to provide arguments. I request at least some documentation on what the difference is. When I run PlantUML from the command line, I have never had to understand any difference (as far as I know).

**Comment by qjebbs** [comment]
Document is here: https://github.com/qjebbs/vscode-plantuml#extension-settings

`commandArgs` provides args to `java`, while `jarArgs` to the jar.

I updated the jar because user has report other bugs of older one, if you encounter problems with integrated jar, another way is to specify your own jar with setting `plantuml.jar`, so that you can keep your own pace updating.

**Comment by sandersaares** [comment]
> Document is here: https://github.com/qjebbs/vscode-plantuml#extension-settings

Yes I saw that but the distinction is not clear enough from what is written there. To run plantUML on the command line, I only type one command with one set of arguments, not two.

**Comment by qjebbs** [comment]
Maybe you can help write better descriptions.😄 

You were not asked to config two, you just find the wrong one. Other users may need java args (`-DPLANTUML_LIMIT_SIZE=8192`), that's why I provide two.

In cmd line,  you still need to decide where to put the args, after `java` or after `plantuml.jar`, don't you? 

Further, arg settings are advanced settings, people who use cmd line args, should assumed to be experts, they knows what they are doing. Or they should shouldn't use them, and try other plan, like: this version of jar has trouble, I switch to another one..

**Comment by sandersaares** [comment]
> Maybe you can help write better descriptions.

Sure, I can try. Let's see.

It might have helped me to more easily find the right setting if they were called "plantumlArgs" and "javaArgs". Some statement along the lines of "These arguments configure the Java runtime. Use jarArgs to configure PlantUML" might also help in the description of "commandArgs".

I immediately started configuring "commandsArgs" when I saw it because, well, I think of "run PlantUML" as the command and did not realize it was somehow split.

> In cmd line, you still need to decide where to put the args, after java or after plantuml.jar, don't you?

I have so far never needed to think about it, no. This is the first time I hear that it may make some difference. I guess my experience so far is always based on online example commands where the parameters are already put in the right place by the author of the example.

> Further, arg settings are advanced settings, people who use cmd line args, should assumed to be experts, they knows what they are doing. Or they shouldn't use them, and try other plans, like: this version of jar has trouble, I switch to another one..

Agreed. It is a rather troublesome situation that the PlantUML defect forces me to think about this!

**Comment by qjebbs** [comment]
Thanks for the advice, the setting names are historical issues, to be honest, I didn't realize we need two arg settings too, that's why I call the first one as "commandArgs". Change it will make current config of many users become invalid, I cannot decide to do so.

I'll take your descriptions first, thanks.
