### ISSUE TITLE
Default click operation should not be zoom in.

### ISSUE THREAD

**Issue by gayanper** [qjebbs/vscode-plantuml#165]
When the diagram doesn't fit the page the default motive operation is to click and drag the diagram. But today the plugin will zoom the selection area if you "click and drag". If you want to move you need to "right click and drag" which is counter intuitive 

A suggestion is to make the "click and drag" actually move the diagram and use "right click and drag" to zoom in a specific area.

**Comment by qjebbs** [comment]
Thanks for feedback, but:

1. If you've ever try some designing software, like CorelDraw, MindManager, you'll find it's usual to have right drag moving
1. The extension is optimized for touchpad (especially Mac): two fingers pan, click (left click) zoom. Touchpad  cannot perform right drag, that's why your ideas cannot applied.

So my suggestion is, get used to it..😀
