### ISSUE TITLE
Costum font in preview but not in export

### ISSUE THREAD

**Issue by MSSandroid** [qjebbs/vscode-plantuml#229]
I set 
`skinparam DefaultFontName "Computer Modern"`

The preview window in vscode shows the UML with the correct font. When I export the diagram to any format (png,svg,eps), the standard font is used and not the defined one. 
This issue exists for both, the local and the server rendering.

I am not very familiar with typescript and vscode plugins and was not able to find the relevant code parts myself.

**Comment by qjebbs** [comment]
Preview image format is always `svg`, while export format could be others, according to you choice. I found different SVG viewer shows different font rendering result, maybe this is the problem.

Anyway, the extension is just a tool who helps you work with `plantuml.jar`, since you had got the image without error, it's not likely to be the extension's problem.
