### ISSUE TITLE
Commenting out @startuml line results in weird behavior

### ISSUE THREAD

**Issue by nielsvanvelzen** [qjebbs/vscode-plantuml#261]
When I tried commenting out the enduml and startuml statements in a diagram I got some weird behavior. I made a small test to reproduce it:

```puml
@startuml EX_01

rectangle EX_01

' @enduml
' @startuml EX_02

rectangle EX_02

@enduml
```
When the cursor is active in the first section (EX_01) an error will be shown "No \@startuml found". The second section (EX_02) only shows the EX_02 rectangle.

I think this problem is caused by the extension by not supporting comments while trying to find all diagrams in a file.

**Comment by qjebbs** [comment]
Consider preview following codes in JavaScript:

```js
// @startuml
// a->b:1
// b->a:2
// @enduml
function hello() {
    console.log(hello);
}
```

That why we should allow characters before `@startuml`, that why `@startuml` starts with special character `@`, and that's why my detect RegExp used to be `/@start(\w+)/i`.

Whenever `@startuml` appears, no matter what is ahead, it's a start of a diagram. Not only the extension, the `Plantuml` project respect this rule too.

I've made changes to detection expression, but this change will make diagrams detection fails when they are inside some languages whose comments start with `'`.

The bad news is, even this won't fix this situation, try using `plantuml.jar` directly without this extension, rendering following code, you will understand what I am saying.

The codes:
```
@startuml
a->b:1
' @startuml
b->a:2
@enduml
```

will be rendered as:

![image](https://user-images.githubusercontent.com/16953333/65656074-0f966c80-e051-11e9-85d4-3c382af3bb1b.png)

See? It still takes `' @startuml` as the start.

Finally, since the change I've made, doesn't solve anything, but introduce new problems, I would like to reverse the change, and remain this issue unsolved.

**Comment by nielsvanvelzen** [comment]
Thanks for looking into this! I didn't try running `plantuml.jar` directly and assumed it would support commenting out the `@startuml` notation. I understand now that this is not the case.

I think reversing this change is indeed the best option.

**Comment by qjebbs** [comment]
Thanks for your understanding😀
