### ISSUE TITLE
Sequence: Several alias syntax is not highlighted

### ISSUE THREAD

**Issue by koara-local** [qjebbs/vscode-plantuml#27]
```
@startuml
    ' OK
    A as "a a a" -> B
    A <- B
    C -> D as "d d d"
    C <- D
    E as "e e e" -> F as "f f f"
    E <- F
    G as "g g g" -> "h h h" as H
    G <- H
    "i i i" as I -> J as "j j j"
    I <- J
@enduml
@startuml
    ' NG
    "a a a" as A -> B
    A <- B
    C -> "d d d" as D
    C <- D
    "e e e" as E -> "f f f" as F
    E <- F
@enduml
```

![image](https://cloud.githubusercontent.com/assets/6697113/25134396/692e29ac-248a-11e7-9139-4c62586c0c83.png)

**Comment by koara-local** [comment]
https://github.com/qjebbs/vscode-plantuml/blob/master/syntaxes/diagram.yaml-tmLanguage#L238

**Comment by qjebbs** [comment]
This is not easy to fix. plantuml syntax is very flexible, it brings conflicts, like:
```
:actor A: -> :actor B: :note: some text
```
![image](https://cloud.githubusercontent.com/assets/16953333/25163368/5f9120da-24fc-11e7-9bf6-34880a8db041.png)


they are all surrounded by ":", but the last part "some note: text" is notes. I have to keeping re-ordering expressions carefully to avoid conflicts like this.

In this case, I may stuck by this problem but I haven't figure out where the problem is.

**Comment by koara-local** [comment]
I also agree that plantuml's "as" is very complicated...
In general I think that it is better to do as follows

```
@startuml

box #LightBlue
    participant A as "name A"
    participant B as "name B"
end box

participant C as "some long name"

A -> B
B -> C

@enduml
```

![image](https://cloud.githubusercontent.com/assets/6697113/25184835/886264e2-2556-11e7-8c17-bdadb188b51b.png)

So it may not be necessary to fix it ...

**Comment by qjebbs** [comment]
fixed. I think the syntax file need refactoring.
