### ISSUE TITLE
Formatter broken in ER diagram

### ISSUE THREAD

**Issue by vlaw** [qjebbs/vscode-plantuml#293]
```
@startuml

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "Entity01" as e01 {
  *e1_id : number <<generated>>
  --
  *name : text
  description : text
}

entity "Entity02" as e02 {
  *e2_id : number <<generated>>
  --
  *e1_id : number <<FK>>
  other_details : text
}

entity "Entity03" as e03 {
  *e3_id : number <<generated>>
  --
  e1_id : number <<FK>>
  other_details : text
}

e01 ||..o{ e02
e01 |o..o{ e03

@enduml
```

After formatting, code became like below:

```
...
e01 ||..o{
    e02
    e01 |o..o{
        e03
```

**Comment by qjebbs** [comment]
Sorry, I have not spare time for formatter, and the plantuml syntax is so flexible.  Basically, current program (parse with `RegExp`) will never always do it right. 

Don't depend on it, only use it when it works right. I'd rather to mark it deprecated, that's why I force to disable it in auto-format cases (format on save).

**Comment by fuhrmanator** [comment]
This is related (if not a duplicate) of https://github.com/qjebbs/vscode-plantuml/issues/327
