### ISSUE TITLE
Feature request: support preview plantuml in markdown

### ISSUE THREAD

**Issue by qiluo** [qjebbs/vscode-plantuml#33]
Hi @qjebbs could you please add preview support if writing plantuml in markdown? We're using gitlab with plantuml server to manage design docs, it supports following syntax to put plantuml in markdown file

    ```plantuml
    Bob -> Alice : hello
    Alice -> Bob : Go Away
    ```
for the details, please refer to [gitlab doc](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/administration/integration/plantuml.md)

**Comment by qjebbs** [comment]
what code can I add to name a diagram?
```
	```plantuml, name="diagram_name", format="png", id="myDiagram", width="200px"
	Bob -> Alice : hello
	Alice -> Bob : Go Away
	```
```

**Comment by qjebbs** [comment]
Gitlab doc says, "You do not need to use the PlantUML diagram delimiters @startuml/@enduml", but I still recommend you use them in this scenario, so that I don't have modify any code, and you get full experience of my plugin.

	```plantuml
	@startuml diagram_name
	Bob -> Alice : hello
	Alice -> Bob : Go Away
	@enduml
	```
PS: PlantUML syntax of "@startuml/@enduml", the goal of it, is to detect PlantUML blocks in any type of document, that is why it starts with "@", in my opinion, so we'd better no break this rule, since there may be always new syntax come out, and one plugin can't deal with all of them.

**Comment by qiluo** [comment]
basically you're right, don't break formal rule. okay, I'll figure out other way

**Comment by qjebbs** [comment]
Thank you for your understanding, but I will still add the ability of list PlantUML blocks (ctrl+shift+o) in MarkDown, as well as Java, JavaScript, C# source files etc, even in plain text.
