### ISSUE TITLE
Support Markdown rendering using inline SVG

### ISSUE THREAD

**Issue by piotrb** [qjebbs/vscode-plantuml#332]
Hi,

My use case is that when I export a markdown document to html .. it still ends up with links to the local plantuml server .. this works well enough if the server is public .. but when running at localhost it makes it a but hard to share .. I'd love if there was an option to make it capture the SVG output from the server and render the diagram using an inline SVG instead of an img link.

**Comment by qjebbs** [comment]
Unfortunately, it's not possible, because markdown-it doesn't allow async functions.

For details, read https://github.com/qjebbs/vscode-plantuml/issues/247#issuecomment-521905062 and it's following posts.

I suggest you change to an public plantuml server, set up your own one if you have privacy concerns.
