### ISSUE TITLE
nailgun fork

### ISSUE THREAD

**Issue by jkeys089** [qjebbs/vscode-plantuml#41]
I just wanted to let you know that I published a fork of your project that uses nailgun to improve preview and export speed.

I doubt you would have any interest since it is a pretty extreme change and does remove some configuration options. However, if you are interested I'd be happy to submit a PR or at least collaborate with you on adding a nailgun option here.

Also, if you have any issues with me publishing to the vscode marketplace please let me know. I left all of the original attributions and donation links in place. I'm certainly not trying to take credit for your work -- I just wanted to go in a slightly different direction :-)

**Comment by qjebbs** [comment]
Thanks buddy. It's OK and welcomed that you make any change to this project, since it's open source.

I am very interested in your work and `nailgun`, because I was ever depressed by the efficiency of starting JVM each time while exporting a diagram. I pulled your branch, but I cannot make it run properly in my PC, maybe I missed something.

[rado0x54](https://github.com/rado0x54) provides a possibility that generating diagrams via plantuml sever(https://github.com/qjebbs/vscode-plantuml/pull/34), the goal of it, is to use this plugin without setting up any environment, and also it's much more faster.

So I cannot help to compare this 2 schemes. Can you help answer some of my doubts?

1. I don't make `previewFromUrlServer` true by default, because setup a sever is out of everyone-capability. Does `nailgun` asks to setup server or clients too?
1. Generating form severe is also much more faster. How is nailgun compares to it?
1. Should I setup nailgun in every user's PC, or just like server, one server in LAN, works for all team members.
1. Server support less formats. I guess nailgun will support all formats, am I right?
1. I suggest you write a how-to about setup the nailgun for plantuml, because I failed on it. ^_^

Traditional way is applicable in most scenarios, it's better to keep it  as the default way, and make others as configurable ways, isn't it?

**Comment by qjebbs** [comment]
I look deeper into it,`nailgun` seems to be much faster than plantuml server, and don't need to manually set up nailgun server, if use `node-plantuml`,  may be fork & customize a new branch of `node-plantuml` is a better way?

**Comment by jkeys089** [comment]
You are right that there is no need to manage a server when using [node-plantuml](https://github.com/markushedvall/node-plantuml). It manages the nailgun server process 100% and shuts it down cleanly on exit.

To be able to support all the features and customization options you currently have it would require some enhancements to [node-plantuml](https://github.com/markushedvall/node-plantuml) (e.g. specifying custom plantuml jar, configurable plantuml command arguments and environment variables, etc...).

I admit I didn't even test the plugin on PC (I normally just work on macOS).
I tried installing the [NG PlantUML plugin](https://marketplace.visualstudio.com/items?itemName=jkeys089.plantuml) from the VS Marketplace this morning on a Win10 PC and it worked OK.

I'm still new to VS Code plugin dev so I'm just guessing here: It is possible there is a conflict with the version of node configured in your local env? I have 7.10.0 installed locally on my Mac (which is what I used to develop / debug the NG plugin). The PC I tested on didn't even have node installed and it was a brand new installation of VS code.

**Comment by qjebbs** [comment]
Yes, your published plugin works. I test it with a file with 9 complex diagrams in it. For complex diagrams, LVM starting time would not be the major cost.

The result is:

Rendering a single diagram by old way takes 11 sec while NG takes 8.6 sec. Much faster, nice.
3-concurrent old way export tasks 38 sec while NG takes 51 sec.

Seems it's a pity that NG missing the concurrent feature.

PS: Preview while export in process, will obviously slow down the export, due to no concurrency support.

**Comment by jkeys089** [comment]
Yes, for batch rendering I think NG's performance gains would be minimal (or possibly even harmful) depending on diagram complexity and available CPU's. I suppose we could start more than one NG process. Unfortunately, that probably wouldn't help much since the first NG render is still relatively slow as it must load all required resources and potentially JIT the hot path's. NG really only has an advantage on re-rendering the same or similar diagrams (e.g. in live preview mode). It might be wise to use NG only for live preview and when concurrency is 1 (e.g. exporting a single diagram or if the user explicitly set max concurrency to 1).

**Comment by qjebbs** [comment]
You are right. Based on our discussion, I think your idea is very good, but it's better to use it after some enhancements to node-plantuml or similar other work.

BTW: On diagram changed or diagram text change, plugin will start a new rendering process, and force kill the previous unfinished one. I don't see the similar logic work in NG version. That means frequent change event will cause obvious delay of the preview result.
