### ISSUE TITLE
No diagrams in preview and exported file

### ISSUE THREAD

**Issue by truezanuda** [qjebbs/vscode-plantuml#435]
Can't preview my diagrams or export them to file.
No errors or some other clues, just blank Preview panel and no files exported.

![image](https://user-images.githubusercontent.com/7686621/132088748-c433902f-858c-4675-8a2b-7caf22cdc91f.png)

**Comment by n9** [comment]
Check logs:

![image](https://user-images.githubusercontent.com/1651867/132326752-7cb8a1c8-5ac4-41b8-a4c5-089d877c459b.png)

**Comment by truezanuda** [comment]
Oh, I was searching this logs output, thank you!
Found out that I have Java Runtime not installed :)

**Comment by fuhrmanator** [comment]
@qjebbs would it be possible to give this feedback in the preview? It's a pretty common problem that people don't configure the plug-in properly, mostly because people expect an install to just work these days (2022). There's even a SO question about this: https://stackoverflow.com/questions/70039939/how-to-use-the-plantuml-preview-in-vscode
