### ISSUE TITLE
`PlantUML Preview` will be launched with` Alt + D` even for non-Diagram files

### ISSUE THREAD

**Issue by koara-local** [qjebbs/vscode-plantuml#7]
Hello. Thank you for a useful plugin.

--

Can I restrict `PlantUML Preview` startup to diagram files only?

For example in Python `PlantUML Preview` will be launched with` Alt + D`.

![python_plantuml](https://cloud.githubusercontent.com/assets/6697113/23387900/a73a6f6c-fda2-11e6-8ef6-f659082f798b.png)

Thank you.

**Comment by koara-local** [comment]
Do you mean that you can write diagrams in comments? If so, I'm sorry.

![python_plantuml2](https://cloud.githubusercontent.com/assets/6697113/23388579/57e4c90e-fda6-11e6-8bef-078f02e3e616.png)

**Comment by qjebbs** [comment]
Yes. I've been thinking about this behavior for a while, I ever disabled for non-diagram document, but enabled it at last. The reason is just as you said, and this is also how plantuml.jar behaves.

![image](https://cloud.githubusercontent.com/assets/16953333/23390414/d0b6a77e-fda8-11e6-9fb2-fd51bf645dc0.png)

Maybe, I should add a setting, leave it to to user to decide?

**Comment by qjebbs** [comment]
Maybe a better way. When alt-D trigged,:
First, I detect if any diagram at cursor. If yes, preview shows. 
If not, I detect if any diagrams in document. If yes, preview still shows, but prompt no valid diagram here. If not, nothing happens.

No setting, not annoying..

**Comment by koara-local** [comment]
It is a very good idea if it can be implemented!
I understand that this is the specification, so I will close this Issue.
thank you for your answer.
