### ISSUE TITLE
%filename% and %filenameNoExtension% are not working

### ISSUE THREAD

**Issue by LucLaf** [qjebbs/vscode-plantuml#80]
Hello,
I have a problem with both %filename% and %filenameNoExtension% when put in the Title. 
The variable name is not substituated.
I use VS Code with the following settings
"plantuml.jar": "D:\\Apps\\PlantUML\\plantuml.1.2017.18.jar",

I have post the problem to PlantUML forum 
[http://forum.plantuml.net/6289/access-to-filename?show=6289]
This is the answer:
_About VS Code, I think the issue comes from the integration between VS Code and PlantUML.  %filename% works with PlantUML command line.
You should explain this issue to the author of the VS Code PlantUML plugin and show him this thread. We would be glad to help him to implements this, but we have to work together on the subject._

Could you do something about that ?

Best Regards.
Luc.

**Comment by qjebbs** [comment]
Similar to what mentioned in that post,

    (Note that this is not working with the online server http://www.plantuml.com/plantuml 
    because there are no "filename" in that case)

The plugin extract diagram source from file, and pipe into `plantuml.jar`, there are no "filename" in this case either.

The problem can be fix only when plantuml pipe provides a parameter that I can pass the filename to it.

**Comment by qjebbs** [comment]
I was expected to solve this with custom definition,

```
-DVAR1=value		To set a preprocessing variable as if '!define VAR1 value' were used
```

But the result doesn't come out as expected.

Source:

```
@startuml test.svg
!define filename test.wsd
note right: %filename%
@enduml
```

Output:

![image](https://user-images.githubusercontent.com/16953333/33158411-cab23716-d044-11e7-9705-17a569809fe8.png)

**Comment by LucLaf** [comment]
Hello!

Thanks for your investigations.
I think you could, has the PlantUML author suggests, have a direct contact with him to solve the problem.
Here is the thread link on the PlantUML Forum
http://forum.plantuml.net/6289/access-to-filename?show=6289#q6289

Regards.

Luc

**Comment by arnaudroques** [comment]
On PlantUML side, we are going to add some command line option (something like filename="test.wsd" ) so that this could be properly managed.
We'll post a message here when ready.

Note that this will works with plugins that launch PlantUML.jar (like yours)

For plugins which use plantuml.com, this won't work. So we are also thinking about either:
* having something some line like `!filename test.wsd` in the source file
* using some none HTTP standard header that will store the desired filename (maybe too complex solution)

**Comment by arnaudroques** [comment]
With last beta http://beta.plantuml.net/plantuml.jar you can have:

`java -jar plantuml.jar -filename "example.puml" -pipe
`

Note that this has not been extensively tested, so do not hesitate to post if you find issues!

**Comment by qjebbs** [comment]
@arnaudroques Thank you for the quick development and reply! I will try this new beta hours later. Can you have a look at another issue too?

http://forum.plantuml.net/6802/bugs-of-generating-image-map-with-pipe

PS: 
I think header solution may have problem in this use case,
User found it OK when preview use plugin or `plantuml.jar`, but not OK when they share a url, because we cannot set header in this case.
