### ISSUE TITLE
"plantuml.includes": ["styles/blue"] doesn't seem to work

### ISSUE THREAD

**Issue by mliq** [qjebbs/vscode-plantuml#85]
Hi, 

I am new to plantUML and this extension is working great, so thank you first of all!

I am interested in different styling so I tried adding `"plantuml.includes": ["styles/blue"]` as stated in the README, but it doesn't seem to do anything.

Any ideas? Also, any other repositories of styles?

Thanks!

**Comment by qjebbs** [comment]
Sorry, busy these days.

Firstly, you need to place the marker `'AutoInclude` in the diagram:
```
@startuml
'AutoInclude
a->b:c
@enduml
```

That's why you saw nothing happen.

But as I tried, even with the [official guard](http://plantuml.com/preprocessing), it still reports error. Seems `plantuml.jar` got problem dealing with `!include` with latest version. Maybe we should report the bug.

**Comment by qjebbs** [comment]
closed due to no feedback

**Comment by m-g-k** [comment]
Hi., so I'm seeing the same problem and have done a few tests. With this in my User Settings:
```
  "plantuml.includes": [
        "styles/blue"
    ]
```

If I preview this diagram:

```
@startuml
'AutoInclude
a->b:c
@enduml
```

I get the usual yellow diagram - the AutoInclude did not work. However, If I include the style directly then it works fine and I see a blue diagram:

```
@startuml
!include "C:\Users\abc\.vscode\extensions\jebbs.plantuml-2.5.7\includes\styles\blue.wsd"
a->b:c
@enduml
```

So the problem seems to be with the AutoInclude itself, rather than with includes in general. 

Let me know if you need any more info, thanks.

**Comment by qjebbs** [comment]
I see, you must tested with new file, and put your config in user setting instead of workspace.

**Comment by m-g-k** [comment]
Hi, thanks for the quick reply. 

I have tested with a new file called "test.puml" only containing:

```
@startuml
'AutoInclude
a->b:c
@enduml
```

I have also tested putting the "plantuml.includes": ["styles/blue"] option in both UserSettings and Workspace and both fail to give a blue diagram when previewed. The only was I can get a blue diagram is by hard coding the include like this:

```
@startuml
!include "C:\Users\abc\.vscode\extensions\jebbs.plantuml-2.5.7\includes\styles\blue.wsd"
a->b:c
@enduml
```

Are there any other tests you need me to run?
