### ISSUE TITLE
cannot supply custom plantuml config file via vscode user settings

### ISSUE THREAD

**Issue by MinnieTheMoocher** [qjebbs/vscode-plantuml#97]
We have a company-global plantuml style file named plantuml.config.

All our toolchains which use plantuml (asciidoc, mediawiki, jira) are configured to use that file
by supplying the option for that file on the command line during plantuml invocation:
`java -jar plantuml.jar -config plantuml.config`

Sadly, your VSCode plugin only offers the user setting
`"plantuml.commandArgs": [],`
, but this goes to the JAVA options, not the PLANTUML options.

This issue requests to get an additional, similar switch which gets supplied to plantuml.jar, not java.

For example, if the new switch would be named "plantuml.jarArgs", then we would like to be able to configure
`"plantuml.jarArgs": ["-config", "plantuml.config"],`
or
`"plantuml.jarArgs": ["-config plantuml.config"],`

**Comment by qjebbs** [comment]
I will add jarArgs in next release, for your case and more others. 

But for your case, I recommend you use [Auto Include](https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml#user-content-about-auto-include), which is:

- More flexible, you can assign which line to insert your style code /  what diagrams to include and what diagrams not to. For example, if you add `-config plantuml.config`, the follow diagram will not be rendered correctly:

    ```
    @startuml
    sudoku 
    @enduml
    ```
- In further development, I may enable auto include support for `server render`. But this could not be done for including via `-config` Arg.

**Comment by MinnieTheMoocher** [comment]
Hmm, no, we not really want to use AutoInclude.
The reason is that each and every file then would have to write the line
`@startuml
'AutoInclude
'contents goes here...
@enduml`
in its beginning.

We want our files completely clean from styles in the header.

Instead, the style is provided company-wide by the plantuml installation itself (plantuml.config),
so that all documents implicitly (not: explicitly) automagically look "right".

**Comment by MinnieTheMoocher** [comment]
Many thanks for the quick reaction and implementation!

**Comment by qjebbs** [comment]
See. Plugin updated, closing this issue now. If you find any problem, re-open it. Thanks.

**Comment by MinnieTheMoocher** [comment]
Thank you. Just tested it. Works exactly as needed/expected.
Thanks again for the fast reaction.

**Comment by woogonchung** [comment]
Hello there.
I tried to follow the discussion between the two of you. Still, I cannot find the way out. My concern is to include three lines of options:
```plantuml
 @startuml
 skinparam ClassAttributeIconSize 0
 skinparam Monochrome true
 hide circle
 ' then, my code starts here ...
 @enduml
```

* I like to have those three lines always automatically to be included (without having @startuml followed by the three options. ) 
* Let's say that I have my own configuration file named "myconfig.puml" which contains the mentioned three lines. How would I configure my vs code setting with my "myconfig.puml" configuration file so that I get my plantuml diagrams to be shown below?

![My Styled UML](https://www.plantuml.com/plantuml/img/LP2nKWCn34HxVuNcgeJ03MbJ9PDGf822-mB7fqays19ZoGqC_uxF-397gVNRNSbxKPiqnm074NRUgcU2Ox0YHZuyVTfauzzyK4t-aXNFZcdmNmZF2-ILYTqjSKJGbD7S_8ZWV781ZN6J7mRD8vB2jm5u0h8HTo0bawvL6Cwd7L2E5qnbti0LzQqmg_M2gce19x6XFtFyaNCIREcUfBh_DRXAB6hktXTA74ASjzk0-ibxiefrhDGxSxpd5UjyJxVj-uUkv7VRhcrXLktniGbhwFj5YzaZZUNNpIy0)

Thank you in advance.
Woogon
